name: Build macOS App on Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true

    - name: Install cargo-packager
      run: cargo install cargo-packager --locked

    - name: Build and package the app
      run: cargo packager --release

    - name: Rename App Bundle
      run: |
        mv target/release/snap2.app snap2.app
        zip -r snap2-macOS.zip snap2.app

    - name: Create and upload release
      uses: softprops/action-gh-release@v2
      with:
        files: snap2-macOS.zip
        name: snap2 ${{ github.ref_name }}
        body: Release for snap2 ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
