name: Build macOS App on Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin, aarch64-apple-darwin

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build macOS App
        run: cargo bundle --release

      - name: Rename App Bundle
        run: |
          mv target/release/bundle/osx/snap2.app snap2.app
          zip -r snap2-macOS.zip snap2.app

      - name: Upload App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap2-macOS
          path: snap2-macOS.zip

      - name: Upload App to Release
        uses: softprops/action-gh-release@v1
        with:
          files: snap2-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}