name: Build macOS App on Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin, aarch64-apple-darwin

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Build macOS App
        run: cargo packager --release

      - name: Upload App as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap2.app
          path: /target/release/snap2.app

      - name: Upload App to Release
        uses: softprops/action-gh-release@v1
        with:
          files: snap2.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}